// Shared tech logo mapping using devicon CDN
const d = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons";
const dl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons";

const logoMap = {
    "Python": `${d}/python/python-original.svg`,
    "JavaScript": `${d}/javascript/javascript-original.svg`,
    "Java": `${d}/java/java-original.svg`,
    "TypeScript": `${d}/typescript/typescript-original.svg`,
    "React": `${d}/react/react-original.svg`,
    "React.js": `${d}/react/react-original.svg`,
    "React 18": `${d}/react/react-original.svg`,
    "React 19": `${d}/react/react-original.svg`,
    "Next.js": `${d}/nextjs/nextjs-original.svg`,
    "Node.js": `${d}/nodejs/nodejs-original.svg`,
    "Express": `${d}/express/express-original.svg`,
    "Express.js": `${d}/express/express-original.svg`,
    "Redux": `${d}/redux/redux-original.svg`,
    "Redux Toolkit": `${d}/redux/redux-original.svg`,
    "MongoDB": `${d}/mongodb/mongodb-original.svg`,
    "MySQL": `${d}/mysql/mysql-original.svg`,
    "Tailwind CSS": `${dl}/tailwindcss/tailwindcss-original.svg`,
    "Firebase": `${d}/firebase/firebase-plain.svg`,
    "Git": `${d}/git/git-original.svg`,
    "GitHub Actions": `${d}/github/github-original.svg`,
    "Docker": `${d}/docker/docker-original.svg`,
    "AWS": `${dl}/amazonwebservices/amazonwebservices-original-wordmark.svg`,
    "PyTorch": `${d}/pytorch/pytorch-original.svg`,
    "Flask": `${d}/flask/flask-original.svg`,
    "FastAPI": `${d}/fastapi/fastapi-original.svg`,
    "Spring Boot": `${d}/spring/spring-original.svg`,
    "Jest": `${d}/jest/jest-plain.svg`,
    "Cypress": `${dl}/cypressio/cypressio-original.svg`,
    "Vite": `${dl}/vitejs/vitejs-original.svg`,
    "CUDA": `${d}/python/python-original.svg`,
    "JWT": `${d}/nodejs/nodejs-original.svg`,
    "ExcelJS": `${d}/nodejs/nodejs-original.svg`,
    "scikit-learn": `${dl}/scikitlearn/scikitlearn-original.svg`,
    "Vercel": `${dl}/vercel/vercel-original.svg`,
    "MIMIC-IV": `${d}/python/python-original.svg`,
    "BioClinicalBERT": `${d}/pytorch/pytorch-original.svg`,
    "ResNet-50": `${d}/pytorch/pytorch-original.svg`,
    "i18next": `${d}/react/react-original.svg`,
    "BeautifulSoup": `${d}/python/python-original.svg`,
    "Sharp/Multer": `${d}/nodejs/nodejs-original.svg`,
    "Sharp": `${d}/nodejs/nodejs-original.svg`,
    "Multer": `${d}/nodejs/nodejs-original.svg`,
    "Framer Motion": `${dl}/framermotion/framermotion-original.svg`,
    "MongoDB Atlas": `${d}/mongodb/mongodb-original.svg`,
    "SBERT": `${d}/python/python-original.svg`,
    "Face Recognition": `${d}/python/python-original.svg`,
    "Audit Middleware": `${d}/nodejs/nodejs-original.svg`,
    "B2B Sales": null,
    "Client Relations": null,
    "Negotiation": null,
    "Teamwork": null,
};

export const getTechLogo = (name) => {
    return logoMap[name] || null;
};
